# Generated by Django 2.2.6 on 2020-09-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('Employee_id', models.IntegerField()),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student1', models.CharField(default=None, max_length=20)),
                ('marks_maths', models.IntegerField()),
                ('marks_science', models.IntegerField()),
                ('marks_english', models.IntegerField()),
            ],
        ),
    ]
